### ISSUE TITLE
Add Unit Test cases for every GITS command.

### ISSUE THREAD

**Issue by kenil-shah** [harshitpatel96/GITS#1]
As of now, the unit test cases have not been implemented for every GITS command that have been implemented for now. We plan to add unit test cases for current GITS command as well as new commands.

**Comment by kenil-shah** [comment]
Currently 4 unit tests for 4 different functionalities have been added. Will be working on adding a few more before the project concludes.

**Comment by faraaz7498** [comment]
- [x] gits_add

- [x] gits_branch

- [x] gits_commit

- [x] gits_create_branch

- [x] gits_delete

- [x] gits_diff

- [x] gits_init

- [x] gits_merge

- [x] gits_profile

- [x] gits_pull

- [x] gits_push

- [x] gits_rebase

- [x] gits_reset

- [x] gits_set

- [x] gits_setupstream

- [x] gits_status

- [x] gits_super_reset

- [x] gits_switch

- [x] gits_sync

- [x] gits_track

- [x] gits_undo

- [x] gits_untrack

- [x] helper

**Comment by rajshrivastava** [comment]
Completed unit test for gits_delete

**Comment by kenil-shah** [comment]
Closing this issue as all the functionalities have been implemented.
