### ISSUE TITLE
Adding gits push workflow(non-master) for pushing the commits

### ISSUE THREAD

**Issue by faraaz7498** [harshitpatel96/GITS#10]
When new changes to be merged are made in a branch other than master: update local master from upstream master, rebase the branch having new changes with the local master, run the test cases ( optional parameter ) and then push.

**Comment by harshitpatel96** [comment]
Added git push workflow
to use the command, you need to do add and commit your files and then the push command would pull from remote branch rebase and then push it.
Command:
gits push
