### ISSUE TITLE
Adding gits sync feature workflow

### ISSUE THREAD

**Issue by faraaz7498** [harshitpatel96/GITS#11]
This feature enables the current branch to be up-to-date with master while keeping the changes in the current branch intact

**Comment by urvishvasani** [comment]
I have implemented this functionality which is useful when the team is working on trunk-based development and the developer needs to keep his/her personal development branch in sync with the main tunk (main/master) in order to avoid any possible merge conflicts in the future.

**Comment by harshitpatel96** [comment]
Implemented by @urvishvasani. Closing the branch.
