### ISSUE TITLE
Adding gits Verified Pull requests support workflow

### ISSUE THREAD

**Issue by faraaz7498** [harshitpatel96/GITS#12]
GitHub has a feature that allows us to make a commit via the web UI. The issue with this is that no unit/functional tests are run and such a commit becomes prone to typing errors, indentation errors and so on which will go unnoticed during review and gets merged to main branches.

A possible solution is to add a checker that determines whether a commit is made from web UI, thereby making it an unverified commit.

**Comment by harshitpatel96** [comment]
No need for a new function, already implemented it in gits pull function.
