### ISSUE TITLE
Adding gits track workflow

### ISSUE THREAD

**Issue by faraaz7498** [harshitpatel96/GITS#16]
A new file which is unmatched by the ignore specification will always be untracked by default.

This feature will enable us to track the file in the project

**Comment by urvishvasani** [comment]
I have implemented this functionality which is used to move files from working directory to staging directory. Only files which are present in the staging directory are considered for the upcoming commits. let me know what you all think about this.

**Comment by kenil-shah** [comment]
Looks good to me. Tested it on a dummy repo.
