### ISSUE TITLE
Changes in how Popen functionality is used

### ISSUE THREAD

**Issue by faraaz7498** [harshitpatel96/GITS#32]
In the entire project, to use the Popen functionality we have used the following coding style

`from subprocess import Popen`
`process = Popen(...)`

For some reason, subprocess.Popen is not getting mocked when using this coding style

So in the entire project, I am changing the coding style to 

`import subprocess`
`process = subprocess.Popen(...)`

**Comment by kenil-shah** [comment]
Closing this issue since the changes are reflected in the master branch
