### ISSUE TITLE
Transform this What documentation to How documentation

### ISSUE THREAD

**Issue by urvishvasani** [harshitpatel96/GITS#9]
Current documentation only describes the purpose of simplified commands. Short examples for each command allow anyone to understand the project better.

**Comment by kenil-shah** [comment]
Started documenting. As of now have kept placeholders for every functionalities. Every functionality would have a brief explanation about what it does and a small example of how the user is supposed to run it (What and How documentation).

**Comment by kenil-shah** [comment]
The following documentation have been transformed:

1] gits commit
2] gits delete
3] gits sync
4] gits create branch

**Comment by urvishvasani** [comment]
I finished this transformation for all other commands. Closing this issue now.
